language: python
dist: xenial
python:
  - 3.6
  - 3.7
install:
  - pip install --upgrade pip
  - pip install flit pytest pytest-cov codecov
  - flit build
  - pip install --pre dist/*.whl
  - pip install pytest pytest-cov codecov
script:
  - pytest --cov tomlfmt
after_success:
  - codecov
