language: python
sudo: false
python:
  - 3.6
install:
  - pip install --upgrade pip
  - pip install flit pytest pytest-cov codecov
  - flit build
  - pip install --pre dist/*.whl
  - pip install pytest pytest-cov codecov
script:
  - pytest --cov tomlfmt
after_success:
  - codecov
matrix:
  include:
    - python: 3.7
      dist: xenial
